//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Album
    {
        public int AlbumID { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}")]
        [Display(Name = "Release Date")]
        public System.DateTime YearReleased { get; set; }
        [Display(Name = "Grammy Winner?")]
        public bool WonGrammy { get; set; }
        [Display(Name = "Album Artwork")]
        public string AlbumPhoto { get; set; }
        public int ArtistID { get; set; }
    
        public virtual Artist Artist { get; set; }
    }
}
